### ISSUE TITLE
Read only lesson?

### ISSUE THREAD

**Issue by cqlanus** [learn-co-curriculum/exiting-loops#8]
This lesson looks to be read only, but the Bootcamp Prep sidebar suggests I need to Fork the lab, Run tests, and Submit. More than that, there is no Open button in the lesson. I've forked the lesson, but it doesn't show up in my Learn IDE because I understand that the Open button Locates/Forks/Clones/Runs npm Install/Opens the lesson automatically.

**Comment by AnnJohn** [comment]
thanks for catching that @cqlanus. we updated this so that it shows up as a Readme.
